name: Build and Deploy MyReact App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: install node
        run: node install

      - name: install dependencies
        run: npm ci

      - name: build
        run: npm run build
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
        - name: deploy
          run: echo "deployed sucessfully"

        
